### ISSUE TITLE
Span parent tracking should be a subscriber concern

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#113]
There should be no parent concepts exposed in `tokio-trace` and `tokio-trace-core`. Subscribers should be able to track the parent span using the enter / exit hooks.

**Comment by carllerche** [comment]
This means no `Subscriber::current_span` function.

**Comment by hawkw** [comment]
@carllerche I agree that tracking the parent span can be up to the subscriber --- I'll remove that from `tokio-trace`. 

However, there are other reasons to have a `current_span` function: 

+ in the `futures` (and `tower`) compat crates, there's a `Instrument::in_current_span` function which instruments a future or stream with the current span. If we remove the  function for returning the current span, we can no longer provide that, so futures would have to be instrumented by passing in a span explicitly. Not providing this may be acceptable; however, I think it's useful to be able to instrument a future or stream or etc without having to thread a handle to that span all the way through the call chain, and allows libraries to propagate spans that were created by user code. 
+ Currently, when a span handle is dropped, the `current_span` function is used to update the handle count on the copy of that span that's set as the current span, if the dropped handle is to the currently executing span. This allows the current span to determine if it can close when it's dropped. Otherwise, once cloned, a span would never close.

  An alternative solution would be adding a function to `Subscriber` that returns the current number of handles to a span with a provided ID. Since we have `Subscriber::clone_span` and `Subscriber::drop_span`, it does make sense for a subscriber to be able to provide a span ref count; however, at the moment, these methods are optional, but if the span closure logic depended on them, they would probably need to be mandatory.

What do you think?

**Comment by hawkw** [comment]
Fixed by #123.
