### ISSUE TITLE
Subscriber::new_id vs. new_span

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#137]
I don't follow why both are needed.

**Comment by hawkw** [comment]
The intention is that one is called with metadata that's valid for the `&'static` lifetime. That metadata may be stored by the subscriber. If the subscriber doesn't need to do any special handling for `'static` meta, `new_span` defaults to just calling `self.new_id()`. 

This is because metadata created by the `span!` macro is always `'static`, but metadata constructed from log records is not. I thought it was better for the subscriber to have the ability to use `'static` metadata in ways it would be unable to use `'a` metadata, since many cases will produce `'static` metadata.

These have been renamed in a96d99fb0d1f804e6cbc8d986ecf0c9bfbdcecb2, and are now called `new_span` (formerly `new_id`) and `new_static` (formerly `new_span`). Hopefully that makes their purposes clearer?

**Comment by hawkw** [comment]
Okay, we can punt on `new_static` for now; right now, I'm using it in the `tokio-trace-log` crate to avoid some allocations, but that code can be rewritten pretty easily.

I agree that the `name` field should probably be `'static`, though.
