### ISSUE TITLE
Fields should contain a callsite::Identifier

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#138]
I don't think that fields should be able to work with the call site, only identify it.

**Comment by hawkw** [comment]
@carllerche the reason I gave `Fields` a `&'static Callsite` rather than a `callsite::Identifier` is because currently, the only way to get an `Identifier` is `Identifier::from_callsite`, and `Fields` has to be constructed statically by the macro. I wanted to avoid making `Identifier`'s `&'static Callsite` a `#[doc(hidden)] pub` field, which AFAIK would be necessary to allow it to be constructed in this way.

WDYT? Should I make `Identifier`'s callsite field `pub`?

**Comment by carllerche** [comment]
In that case, I think creating an `Identifier` can be public. The details of callsites are a `tokio-trace` macro concern, so it feels ok to make `Identifier` construction public.

**Comment by hawkw** [comment]
@carllerche Okay, sounds good to me --- I'll make that change.
