### ISSUE TITLE
There should be no required syscalls in the instrumentation API

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#24]
Currently, it looks like `Instant::now()` is being called in the `span!` macro. Syscalls are pretty expensive and the subscriber might not care about the time value. The instrumentation API should not call `Instant::now()`. Instead, it should be up to the subscriber to track time if it cares.

**Comment by hawkw** [comment]
I agree with this change (and we should also remove `Instant`s from the `Subscriber::enter` and `Subscriber::exit` functions). 

The motivation for each span having a creation timestamp was that there might be some delay between span creation and when a subscriber sees it, if it is not entered immediately. Similarly, the motivation for passing timestamps to `enter` and `exit` was that it seemed good to record one timestamp for span entry/exit, so that all the subscribers see the entry/exit occurring at the same time, regardless of the order in which the event is broadcast to them. In practice, I'm not sure how much those considerations matter, compared to the potential overhead of making syscalls that we don't need the result of.

**Comment by hawkw** [comment]
I have [a branch](https://github.com/hawkw/tokio-trace-prototype/compare/eliza/remove-timestamps?expand=1) that removes all the `Instant`s from spans.

However, there's a bit of an issue with that change in the current implementation: it means that span equality (and hashing) is based entirely on what call site the span originated at. 

Previously, span equality was based on comparing the span's metadata _and timestamp_, with the timestamp disambiguating spans originating at the same location but created at different times. If we remove the timestamp and want different instances of the same span to be different, we'd need to change their equality and hashes to be based on the values of their fields. If `Value`s are represented by trait objects, the value trait cannot require `Hash` or `PartialEq`, because those traits are not object safe. Therefore, it seems like this is blocked on changing span values to not be trait objects (see #32).

**Comment by carllerche** [comment]
Why does a span need to implement equality or hash?

**Comment by hawkw** [comment]
@carllerche I think that if a subscriber may see a given span multiple times, it's probably good to be able to distinguish between them. I suppose the other solution, rather than blocking this on figuring out #32, is to introduce a notion of span IDs, which we probably ought to have anyway.

**Comment by carllerche** [comment]
Yes, I believe a span identifier is a better option.

In my original sketch, the span is passed to the subscriber on creation and the subscriber returns an opaque identifier.
