### ISSUE TITLE
It should be possible to add fields to spans over time.

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#26]
All data that we wish to associate with a span may not be known when the span is created. Additional data might be discovered during the execution of the span. It should be possible to associate data with a span throughout its execution.

**Comment by hawkw** [comment]
I'm not sure how to reconcile this with 

Not allowing fields to be added to a span was an intentional design decision, although I'm open to changing my mind. Here's some of my motivations:
+ How would subscribers be informed of the added field? Do they receive a notification specific to adding a field (adding another method to the `Subscriber` API), or do they just see the span with the added fields the next time the span is entered or exited?
+ If spans are shared (between multiple span handles, the thread local current span, etc), they need some kind of internal mutability. Even if we remove the constraint that multiple threads be able to enter a span, I think we would still want span data to be sharable between threads, such as in a case where a subscriber forwards span data to a dedicated processing thread. Therefore, we would need to wrap the span's fields in a `Mutex`...
+ Not allowing new fields to be added means that all spans originating at a given call site can share the same set of field names in their (statically constructed) metadata, rather than having their own copies of the field names that have to be constructed at runtime. Besides reducing the size of the span data, this also means that subscribers can filter based on field names, making it possible to subscribe to only the spans with a particular field.
+ The current API _does_ provide a way of associating new data with a span after it has begun executing: create a new child span with the new fields. Given that a span is considered to be "executing" while its children are executing, this doesn't require us to enter the. span we want to add new fields to, and spans have an `all_fields` iterator that lets us iterate over all the fields of a span _and its parents_ (with duplicated field names using the value defined by the descendant span). 
  Therefore, if we have some span `Foo` with fields `a` and `b`, and we create a new child span `Bar` with field `c`, `Bar`s `all_fields` iterator will contain `a`, `b`, and `c`. `Foo` will be considered "running" while we are inside of `Bar`, so we have essentially added a field to `Foo` (for the duration of `Bar`).
  Adding new fields using child spans also seems easier for subscribers to process, as it's based on a concept that the subscriber API already understands (the parent-child relationship).

Furthermore, I have to wonder how we would reconcile adding new fields to a span with the desire to avoid allocations expressed in #25. How would we safely add a new field besides inserting it into a growable collection like a `Vec` or `HashMap`, that might allocate?

**Comment by hawkw** [comment]
@carllerche (and @davidbarsky), unless you have any significant disagreements with the rationale I gave in https://github.com/hawkw/tokio-trace-prototype/issues/26#issuecomment-426403207, I think adding documentation that explains why spans are immutable and recommends creating subspans as an alternative should be sufficient to close this issue.

**Comment by carllerche** [comment]
> How would subscribers be informed of the added field? Do they receive a notification specific to adding a field (adding another method to the Subscriber API), or do they just see the span with the added fields the next time the span is entered or exited?

Yes, a new subscriber API is added to add fields.

> If spans are shared (between multiple span handles, the thread local current span, etc), they need some kind of internal mutability.

As per #28, I do not think this should be the case. It should only be possible to add fields w/ a handle that cannot have clones.

> Not allowing new fields to be added means that all spans originating at a given call site can share the same set of field names in their (statically constructed) metadata, rather than having their own copies of the field names that have to be constructed at runtime.

Having a set of fields known up front has value, but it is not clear that providing all the *values* up front is a requirement for this.

The `span!` macro could define all the fields while allowing the values to be provided over time.

> create a new child span with the new fields

This has a different semantic meaning.

> Furthermore, I have to wonder how we would reconcile adding new fields to a span with the desire to avoid allocations expressed in #25. 

Passing the field directly to the subscriber via a fn call does not require allocations. Again, I'm trying to push to move **away** from having the *instrumentation* api track any of these fields, instead punting to the subscriber.

**Comment by carllerche** [comment]
Given how futures are lazy, using them has a two step process. First, you create the future, then you `poll` it. When the future is created, it won't necessarily know its parent. It only knows the parent on poll. This implies that the span won't necessarily have access to all data at creation time.

I am open to punting this requirement for now and see how using tokio-trace works out w/o being able to pass values during execution, but most of the points above still hold either way.

**Comment by davidbarsky** [comment]
I don't really have strong opinions on this, and I'll defer to @carllerche and @hawkw's judgement.

**Comment by carllerche** [comment]
My tl;dr is that it is fine to punt pushing field values after span creation until we find a strong use case for it...

**Comment by davidbarsky** [comment]
Agreed. There are lot of things up in the air, and I’m happy to take a wait-and-see approach.

**Comment by hawkw** [comment]
I've been thinking about this a bit, and I'm open to making it possible to add field values after the span is created, provided that we do it in such a way that subscribers can still filter based on field names (i.e. we allow adding _values_ to fields after creation, but not adding _new fields_, like @carllerche suggested in https://github.com/hawkw/tokio-trace-prototype/issues/26#issuecomment-427591043).

I think it's probably best to add this functionality either as part of or as a follow-up to a broader change that makes subscribers responsible for owning span data, rather than always reference-counting it as we do currently. I'm considering that change to reduce allocation in the instrumentation API (see #25), but I think it would also make it easier to allow span fields to be added after creation as well.
