### ISSUE TITLE
A subscriber filtering events (using `enabled`) should not require string comparisons on every call

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#27]
Subscriber filter rules can be expensive (multiple regexes / string comparisons). Having to do this filter check every time a span is created would be prohibitively expensive.

Instead, the check should only have to be done one time per call site in the common case.

**Comment by carllerche** [comment]
The requirement is that a span / event that is not subscribed to is as close to a no-op as possible. I would like the target to be a relaxed atomic load.

**Comment by hawkw** [comment]
As a very rough sketch, perhaps something like this:
```rust
macro_rules! span {
    ($name:expr) => { span!($name,) };
    ($name:expr, $($k:ident = $val:expr),*) => {
        {
            use std::sync::atomic::{AtomicUsize, Ordering};
            use $crate::{span, Subscriber, Dispatcher, Meta};
            static META: Meta<'static> = static_meta!($name, $($k),* );
            static FILTERED: AtomicUsize = ATOMIC_USIZE_INIT;
            const NOT_FILTERED: usize = 0;
            const ENABLED: usize = 1;
            const DISABLED: usize = 2;
            if match FILTERED.load(Ordering::Relaxed) {
                NOT_FILTERED => {
                    let enabled = Dispatcher::current().enabled(&META);
                    if enabled {
                        FILTERED.store(ENABLED, Ordering::Relaxed);
                    } else {
                        FILTERED.store(DISABLED, Ordering::Relaxed);
                    }
                    enabled
                },
                ENABLED => true,
                DISABLED => false,
            } {
                span::Span::new(
                    // ...
                )
            } else {
                span::Span::new_disabled()
            }
        }
    }
}
```

If we wanted to allow subscribers to change their filter configurations, we could add a method like "should_invalidate_filters(&self) -> bool` to the `Subscriber` API, and check that first before checking the cached filter state.

**Comment by carllerche** [comment]
Another use case to support: a sampling subscriber.

For example, maybe the subscriber only wants to pull the span every 1000 traces.

**Comment by hawkw** [comment]
I've started on [an implementation](https://github.com/hawkw/tokio-trace-prototype/compare/eliza/cache-filter?expand=1) based on the approach I described in https://github.com/hawkw/tokio-trace-prototype/issues/27#issuecomment-426414664, it seems to work correctly thus far (and passes the handful of tests I wrote for the caching behaviour). That branch isn't quite ready to merge --- currently, there's no way for subscribers to invalidate their cached filter results, so it won't work for subscribers that want to update their filters.

However, I did realize that there's a potential issue with that approach and the changes suggested in #30. Storing an `AtomicUsize` at each call site works fine when there's a single global subscriber that doesn't change during the lifetime of the process; but if the subscriber is per-task or otherwise contextual, like how #30 proposes, the value of `FILTERED` may no longer be valid. 

To get around that, we'd either need to make subscribers responsible for storing the filter result (which adds state back to subscribers and runs into the problems I described in https://github.com/hawkw/tokio-trace-prototype/issues/27#issuecomment-426379366), or ensure that subscribers always invalidate their cached filter results when switching the subscriber context, which...still seems to imply some kind of subscriber state. This may require further thought.

@carllerche 
> Another use case to support: a sampling subscriber.

I think a sampling subscriber would be able to use a subscriber trait method that invalidates cached filters in the same way that a subscriber that wants to change its filter would, but it would have to do so by having that function always return `true` so that the filter result is never re-used. This could be potentially confusing for subscriber authors, without sufficient documentation...

**Comment by carllerche** [comment]
> However, I did realize that there's a potential issue with that approach and the changes suggested in #30. Storing an AtomicUsize at each call site works fine when there's a single global subscriber that doesn't change during the lifetime of the process; but if the subscriber is per-task or otherwise contextual, like how #30 proposes, the value of FILTERED may no longer be valid.

The solution is to bust the cache anytime it might become invalid. i.e. if a new subscriber is registered somewhere, the cache is busted.

**Comment by hawkw** [comment]
@carllerche yes, that's right, and it should be possible, it's just some additional complexity.
