### ISSUE TITLE
A dispatcher should only contain one subscriber

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#29]
I do not see a reason to have the dispatcher contain multiple subscribers. If fanout behavior is required, that can be implemented with a `FanoutSubscriber` that does this logic.

Following this path removes most reasons to have `Dispatcher` in the core crate.

**Comment by hawkw** [comment]
Yeah, I've been thinking about making this change as well --- the current dispatcher implementation was one of the first things I wrote, and I realised that it wasn't strictly necessary as the fanout could just be performed by a `Subscriber` implementation. I hadn't removed it yet mainly because I was focused on getting a working prototype.
