### ISSUE TITLE
There should be no global subscriber state

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#30]
Following Tokio patterns (and departing from `log`), there should be no global subscriber state.

The Tokio runtime will handle setting up the subscriber at the root of the task. When operating outside of a Tokio runtime, the user will be responsible for setting up the necessary subscriber. There should be a way to get a handle to the current subscriber and probably easy ways to get into new execution while carrying over the subscriber.

We can always back out of this by adding global state later, but we cannot remove global state without a breaking change.

**Comment by hawkw** [comment]
I'm onboard with this change as well --- the current global subscriber was based on what the `log` crate does, and I'm not sure if replicating that was the right thing to do. 

This would also have the nice side benefit of making testing much easier. I had previously hit some issues writing tests with a mock subscriber that expects certain events, since all the test _threads_ created by running the unit tests all shared the same _process-global_ subscriber --- I had to [hack around this](https://github.com/hawkw/tokio-trace-prototype/blob/d782db13b8d35dbf8091a511713c4cf1f3d5aa1d/tokio-trace/src/subscriber.rs#L141-L175) for testing purposes, which didn't really seem ideal...
