### ISSUE TITLE
Why are field values trait objects?

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#32]
How is the subscriber expected to extract meaning with an opaque value? For example, if the field value contains a number (for example, current queue depth), what is the subscriber supposed to do with this?

Is it expected that the subscriber do a typecast for each value?

Instead, has it been considered to limit field values to a set of primitive types? What are the pros / cons?

Is there a real use case that requires trait objects for values?

**Comment by hawkw** [comment]
The current implementation of field values is a bit of a placeholder. It seems like there was some prior discussion (https://github.com/tokio-rs/tokio/issues/561#issuecomment-415274073, https://github.com/tokio-rs/tokio/issues/561#issuecomment-415521974) of how to represent field values, but that no conclusive decision had been reached. 

I thought there might be some value in being able to attach arbitrarily typed values to trace events, so I didn't want to rule that out yet. I had looked at [`slog::Value`](https://docs.rs/slog/2.4.0/slog/trait.Value.html) and at [proposed changes to the `log` crate](https://github.com/rust-lang-nursery/log/issues/149#issuecomment-403334128) as prior art, and thought that treating values as a trait object as a placeholder would allow a more featureful `Value` trait to be added eventually.

I've also considered alternatives like restricting them to a set of primitives, or making them `Any` so that downcasting is easier. I'm not sure if either of those are ideal.

**Comment by hawkw** [comment]
I'd like to hear from @davidbarsky on this as well, since the motivation for not limiting span values to primitive types is partially due to his comments.

**Comment by carllerche** [comment]
@davidbarsky all good, we are exploring the space.

It also will be possible to add dynamic values in the future.

**Comment by carllerche** [comment]
I would prefer to avoid an enum.

**Comment by hawkw** [comment]
@carllerche What would you propose as an alternative to an enum, besides a trait object?

**Comment by carllerche** [comment]
I guess it depends on the rest of the details. In my sketch, I was heading down the path of having a subscriber trait fn per value type.
