### ISSUE TITLE
Why is `Meta.name` optional?

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#77]
It looks like the optional name is the only difference between `Meta::new_span` and `Meta::new_event`.

Edit: I guess `Kind` too. Could you explain why there is a differentiation between spans and events at the `Meta` level?

**Comment by hawkw** [comment]
@carllerche 
`Meta.name` is optional because only `Span`s have `&'static str` names; `Event`s have messages (`fmt::Arguments`) rather than names. Span names may go in the metadata as they live for the `'static` lifetime, while `Event` messages are not guaranteed to be `'static` (such as when `Event`s are generated from log records with generic lifetimes).

I thought span names ought to go in the metadata so that subscribers may filter based on names --- we might want to exclude a certain set of span names, or only enable particular spans, et cetera.

> Could you explain why there is a differentiation between spans and events at the `Meta` level?

Yes. The metadata distinguishes between spans and events because I thought it seemed reasonable for a subscriber to want to enable only events or only spans. The field was added in #44, along with filters in the `-subscriber` crate for enabling only events or only spans; see also #36.
