### ISSUE TITLE
Why does `Event` have two lifetimes?

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#78]
The comments say:

```rust
/// **Note**: `Event` must be generic over two lifetimes, that of `Event` itself
/// (the `'event` lifetime) *and* the lifetime of the event's metadata (the
/// `'meta` lifetime), which must be at least as long as the event's lifetime.
/// This is because the metadata may live as long as the lifetime, or it may be
/// `'static` and reused for all `Event`s generated from a particular source
/// code location (as is the case when the event is produced by the `event!`
/// macro). Consumers of `Event` probably do not need to actually care about
/// these lifetimes, however.
```

However, this doesn't explain why it is necessary vs. constructing the `Event` with a single, more conservative, lifetime.

**Comment by hawkw** [comment]
I think at one point there may have been an issue where the code generated `event!` macro failed to compile because the lifetime was inferred to be `'static`, since the metadata was `'static`, and the fields added to the event could not be borrowed for the `'static` lifetime. 

However, I just tried removing the second lifetime, and I believe this is no longer necessary --- the code still compiles when `Event` is parameterized over a single lifetime. I'll put a branch up to fix this.
